stages:
  download:
    cmd: moviesurfer data download
    deps:
      - moviesurfer/cli/data/download.py
      - moviesurfer/data/download_data.py
    outs:
      - data/raw/ml-25m
  train-test-split:
    cmd: moviesurfer data train-test-split
    deps:
      - moviesurfer/cli/data/split.py
      - moviesurfer/data/split.py
      - data/raw/ml-25m
    outs:
      - data/processed/ml-25m
  train-most-popular:
    cmd: python prototypes/most-popular/main.py train ./data ./models
    deps:
      - prototypes/most-popular/main.py
      - data/processed/ml-25m
    outs:
      - models/most-popular
